In [1]:
import numpy as np

In [2]:
matrix  = np.array([[1,2,3], [4,5,6], [7, 8, 9]])

In [3]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
matrix.shape

(3, 3)

In [6]:
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [7]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
matrix_100 = matrix + 100

In [9]:
matrix_mul_100 = matrix * 100

In [10]:
matrix_100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [11]:
matrix_mul_100

array([[100, 200, 300],
       [400, 500, 600],
       [700, 800, 900]])

In [14]:
matrix = np.random.randint(35, size=(3, 3))

In [21]:
matrix.max(axis=0)

array([24, 19, 32])

In [16]:
matrix

array([[24,  2, 10],
       [14, 16, 32],
       [22, 19, 23]])

In [20]:
matrix.mean(axis=0)

array([20.        , 12.33333333, 21.66666667])

In [29]:
matrix  = np.random.randint(100, size=(4,4))

In [31]:
matrix.T

array([[47, 91, 23, 68],
       [28,  7, 71, 76],
       [27, 23, 74, 49],
       [43, 37, 16, 44]])

In [32]:
matrix

array([[47, 28, 27, 43],
       [91,  7, 23, 37],
       [23, 71, 74, 16],
       [68, 76, 49, 44]])

In [33]:
np.linalg.det(matrix)

4608064.999999994

In [34]:
matrix.diagonal()

array([47,  7, 74, 44])

In [35]:
matrix.trace()

172

In [36]:
np.linalg.eig(matrix)

(array([175.87194667 +0.j       , -19.81332396+18.4455401j,
        -19.81332396-18.4455401j,  35.75470126 +0.j       ]),
 array([[ 0.40910192+0.j        ,  0.09012729+0.30463234j,
          0.09012729-0.30463234j,  0.21791452+0.j        ],
        [ 0.42743192+0.j        ,  0.63211444+0.j        ,
          0.63211444-0.j        ,  0.33918047+0.j        ],
        [ 0.49072482+0.j        , -0.41016788-0.09093699j,
         -0.41016788+0.09093699j, -0.87408869+0.j        ],
        [ 0.63963015+0.j        , -0.42477868-0.37757568j,
         -0.42477868+0.37757568j,  0.27099599+0.j        ]]))

In [38]:
vector_a = np.random.randint(100, size=(4,3))
vector_b = np.random.randint(100, size=(4,3))

In [41]:
vector_a, vector_b

(array([[28, 50, 67],
        [91, 88, 27],
        [83,  8, 95],
        [95, 62, 94]]), array([[74, 65, 62],
        [22, 95, 25],
        [98, 20, 69],
        [46, 71, 75]]))

In [40]:
np.add(vector_a, vector_b)

array([[102, 115, 129],
       [113, 183,  52],
       [181,  28, 164],
       [141, 133, 169]])

In [43]:
vector_c = np.random.randint(26, size=(2,2))

In [45]:
np.linalg.inv(vector_c)

array([[-0.00621118,  0.0621118 ],
       [ 0.10559006, -0.05590062]])